curl 'http://localhost:8080/api/v1/upload' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en;q=0.9,en-US;q=0.8,bn;q=0.7,es;q=0.6,fr;q=0.5' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryU9dIfeTkKCVElnQL' \
  -H 'dnt: 1' \
  -H 'origin: https://strong.data.mtanzim.com' \
  -H 'priority: u=1, i' \
  -H 'referer: https://strong.data.mtanzim.com/' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  --data-raw $'------WebKitFormBoundaryU9dIfeTkKCVElnQL\r\nContent-Disposition: form-data; name="myFile"; filename="strong5161343309978073228.csv"\r\nContent-Type: text/csv\r\n\r\n\r\n------WebKitFormBoundaryU9dIfeTkKCVElnQL--\r\n'